version: '3.8'

services:
  # Web E-commerce Application (Backend + Frontend)
  web-ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-ecommerce:latest
    container_name: web-ecommerce-app
    restart: unless-stopped
    ports:
      - "3000:3000"  # Frontend
      - "5000:5000"  # Backend
    environment:
      # Database - Kết nối với XAMPP MySQL
      DATABASE_URL: "mysql://root:@host.docker.internal:3306/ecommerce_db"
      
      # JWT
      JWT_SECRET: "your-super-secret-jwt-key-change-in-production-123456789"
      JWT_EXPIRES_IN: "24h"
      JWT_REFRESH_EXPIRES_IN: "7d"
      
      # Server
      PORT: 5000
      NODE_ENV: "production"
      
      # Frontend
      FRONTEND_URL: "http://localhost:3000"
      
      # Cloudinary (thay đổi theo tài khoản của bạn)
      CLOUDINARY_CLOUD_NAME: "your_cloud_name"
      CLOUDINARY_API_KEY: "your_api_key"
      CLOUDINARY_API_SECRET: "your_api_secret"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s